	jobs: I dont understend what is the problem????
	  build:
	    name: Hello world action
	    runs-on: ubuntu-latest
	    steps:
	      - uses: actions/checkout@v1
	      - uses: ./action-a
	        with:
          MY_NAME: "Mona"
